### ISSUE TITLE
Compile problem with ./tfjs_binding

### ISSUE THREAD

**Issue by sami-badawi** [sami-badawi/tensorflow-typescript-starter#2]
Upgrade to "@tensorflow/tfjs-node": "^0.3.0" and new compile error appeared:

```
> tfjs-examples-mnist-node@0.1.0 build /Users/samibadawi/samicode/tensorflow-typescript-starter
> tsc

node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.d.ts:20:40 - error TS2307: Cannot find module './tfjs_binding'.

20 import { TFEOpAttr, TFJSBinding } from './tfjs_binding';
                                          ~~~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by ramlongcat** [comment]
just add `"skipLibCheck": true` in your tsconfig.json and it should work.
it works on my machine running TypeScript 3.5.1
